### ISSUE TITLE
Pluging won't work anymore with next 13.3.1 (tested with up to canary 18)

### ISSUE THREAD

**Issue by shouze** [blitz-js/next-superjson-plugin#76]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /app/.env.development
warn  - You have enabled experimental feature (swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/app/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/app/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at /app/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: out of bounds memory access
           at <unnamed> (<module>[883]:0xe1575)
           at <unnamed> (<module>[905]:0xe6e76)
           at <unnamed> (<module>[907]:0xe8272)
           at <unnamed> (<module>[370]:0x5938e)
           at <unnamed> (<module>[442]:0x6c2b6)
           at <unnamed> (<module>[659]:0xa7b7b)
           at <unnamed> (<module>[686]:0xb3136)
           at <unnamed> (<module>[633]:0x9a0ed)
           at <unnamed> (<module>[52]:0x709c)
           at <unnamed> (<module>[51]:0x6e13)
           at <unnamed> (<module>[763]:0xbc183)
           at <unnamed> (<module>[1876]:0x1657de)
    2: heap_get_oob

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: _ZZN4node14ThreadPoolWork12ScheduleWorkEvENUlP9uv_work_sE_4_FUNES2_
  12: worker
             at /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:122:5
  13: start_thread
  14: clone', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.37/src/impls/core/mod.rs:265:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/app/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/app/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at /app/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: unreachable
           at <unnamed> (<module>[1683]:0x154169)
           at <unnamed> (<module>[1676]:0x153ec1)
           at <unnamed> (<module>[1675]:0x153e3e)
           at <unnamed> (<module>[1661]:0x15309f)
           at <unnamed> (<module>[1660]:0x152fde)
           at <unnamed> (<module>[1670]:0x15378e)
           at <unnamed> (<module>[1765]:0x159d95)
           at <unnamed> (<module>[1812]:0x160b1f)
           at <unnamed> (<module>[933]:0xf820b)
           at <unnamed> (<module>[934]:0xf837e)
           at <unnamed> (<module>[933]:0xf7c62)
           at <unnamed> (<module>[661]:0xa9181)
           at <unnamed> (<module>[659]:0xa7ac0)
           at <unnamed> (<module>[686]:0xb3136)
           at <unnamed> (<module>[633]:0x9a0ed)
           at <unnamed> (<module>[52]:0x709c)
           at <unnamed> (<module>[51]:0x6e13)
           at <unnamed> (<module>[763]:0xbc183)
           at <unnamed> (<module>[1876]:0x1657de)
    2: unreachable

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: _ZZN4node14ThreadPoolWork12ScheduleWorkEvENUlP9uv_work_sE_4_FUNES2_
  12: worker
             at /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:122:5
  13: start_thread
  14: clone', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/app/src/pages/_app.page.tsx")'

Caused by:
    0: failed to invoke `/app/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at /app/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: out of bounds memory access
           at <unnamed> (<module>[905]:0xe6d63)
           at <unnamed> (<module>[907]:0xe8272)
           at <unnamed> (<module>[905]:0xe7449)
           at <unnamed> (<module>[371]:0x5aac1)
           at <unnamed> (<module>[442]:0x6c34e)
           at <unnamed> (<module>[659]:0xa7b7b)
           at <unnamed> (<module>[686]:0xb3136)
           at <unnamed> (<module>[633]:0x9a0ed)
           at <unnamed> (<module>[52]:0x709c)
           at <unnamed> (<module>[51]:0x6e13)
           at <unnamed> (<module>[763]:0xbc183)
           at <unnamed> (<module>[1876]:0x1657de)
    2: heap_get_oob

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: _ZZN4node14ThreadPoolWork12ScheduleWorkEvENUlP9uv_work_sE_4_FUNES2_
  12: worker
             at /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:122:5
  13: start_thread
  14: clone', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'assertion failed: prev.start > max', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:224:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.0-beta.2/src/engine/trap/frame_info.rs:220:39
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

to work as usual

### Version

0.5.6

### Config

```javascript
experimental: {
      swcPlugins: [
        ["next-superjson-plugin", {}],
    },
```

### Additional context

Looks like related to https://github.com/vercel/next.js/pull/48521 and/or https://github.com/vercel/next.js/pull/48098 and probably https://github.com/swc-project/swc/pull/7170

**Comment by darthmaim** [comment]
See #74, it has been broken for some time (and the PRs you mentioned are actually part of the fix to get this working again)
